# Generated by Django 3.0.4 on 2020-03-11 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phoneapp', '0003_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Toolimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='toolimg')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolimg', to='phoneapp.Tool', verbose_name='所属标题')),
            ],
        ),
    ]
