# Generated by Django 3.0.4 on 2020-03-11 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoneapp', '0004_tool_toolimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolimg',
            old_name='title',
            new_name='tool',
        ),
    ]
