# Generated by Django 3.0.4 on 2020-03-11 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoneapp', '0006_personal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='personal',
            new_name='Personaly',
        ),
    ]
