# Generated by Django 3.0.4 on 2020-03-11 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoneapp', '0007_auto_20200311_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='good',
            name='price',
        ),
        migrations.RemoveField(
            model_name='good',
            name='view',
        ),
    ]
