# Generated by Django 3.0.4 on 2020-03-11 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phoneapp', '0009_auto_20200311_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgood',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sgoods', to='phoneapp.Good', verbose_name='小分类'),
        ),
    ]
