# Generated by Django 3.0.4 on 2020-03-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoneapp', '0010_auto_20200311_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sgood',
            old_name='category',
            new_name='good',
        ),
    ]
